# Generated by Django 4.2.4 on 2026-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_office_admin',
            field=models.BooleanField(default=False),
        ),
    ]
