# Generated by Django 4.2.4 on 2023-09-27 07:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        ('employees', '0001_initial'),
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('event_desc', models.CharField(max_length=1000)),
                ('participants', models.CharField(max_length=500)),
                ('event_location', models.CharField(max_length=255)),
                ('event_day_start', models.CharField(max_length=10)),
                ('event_month_start', models.CharField(max_length=10)),
                ('event_year_start', models.CharField(max_length=10)),
                ('event_time_start', models.CharField(max_length=50)),
                ('event_day_end', models.CharField(max_length=10)),
                ('event_month_end', models.CharField(max_length=10)),
                ('event_year_end', models.CharField(max_length=10)),
                ('event_time_end', models.CharField(max_length=50)),
                ('whole_date_start', models.DateField(default=datetime.date.today)),
                ('whole_date_end', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.division')),
                ('f_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
