# Generated by Django 4.2.4 on 2023-10-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
