# Generated by Django 4.2.4 on 2023-10-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='f_emp',
        ),
    ]
