# Generated by Django 4.2.4 on 2023-10-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_f_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='whole_date_end_searchable',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='whole_date_start_searchable',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
