# Generated by Django 4.2.4 on 2023-10-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_whole_date_end_searchable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='office',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
