# Generated by Django 4.2.4 on 2023-10-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='org_outcome',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='paps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='unit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
