# Generated by Django 4.2.4 on 2023-10-26 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_org_outcome_event_paps_event_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='division_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='whole_dateEnd_with_time',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='whole_dateStart_with_time',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
