# Generated by Django 4.2.4 on 2023-11-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_actual_outcome_event_calendar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_location_barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
