# Generated by Django 4.2.4 on 2023-11-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_event_location_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_day_start',
            field=models.IntegerField(max_length=10),
        ),
    ]
