# Generated by Django 4.2.4 on 2023-11-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_event_day_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_day_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_day_start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_month_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_month_start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_year_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_year_start',
            field=models.IntegerField(),
        ),
    ]
