# Generated by Django 4.2.4 on 2023-11-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_event_day_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
