# Generated by Django 4.2.4 on 2023-12-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_all_day',
            field=models.BooleanField(default=False),
        ),
    ]
