# Generated by Django 4.2.4 on 2023-12-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_event_all_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='whole_date_start_searchable',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
