# Generated by Django 4.2.4 on 2023-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_whole_date_start_searchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='whole_date_start_searchable',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
