# Generated by Django 4.2.4 on 2023-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_whole_date_start_searchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='file_attachment',
            field=models.FileField(default='NONE', upload_to='media/'),
        ),
    ]
