# Generated by Django 4.2.4 on 2023-12-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='whole_date_end_searchable',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
