# Generated by Django 4.2.4 on 2024-01-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paps', '0002_pap_oo_name'),
        ('lgus', '0003_alter_lgu_created_at_alter_lgu_updated_at'),
        ('orgoutcomes', '0002_rename_paps_orgoutcome_description'),
        ('provinces', '0002_alter_province_created_at_alter_province_updated_at'),
        ('barangays', '0002_alter_barangay_province'),
        ('events', '0018_alter_event_whole_date_end_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='barangay',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='barangays.barangay'),
        ),
        migrations.AddField(
            model_name='event',
            name='lgu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lgus.lgu'),
        ),
        migrations.AddField(
            model_name='event',
            name='orgoutcome',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orgoutcomes.orgoutcome'),
        ),
        migrations.AddField(
            model_name='event',
            name='pap',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paps.pap'),
        ),
        migrations.AddField(
            model_name='event',
            name='province',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='provinces.province'),
        ),
    ]
