# Generated by Django 4.2.4 on 2024-01-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_division_name'),
        ('events', '0019_event_barangay_event_lgu_event_orgoutcome_event_pap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='unit_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
        ),
    ]
