# Generated by Django 4.2.4 on 2024-02-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_display_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_status',
            field=models.BooleanField(default=True),
        ),
    ]
