# Generated by Django 4.2.4 on 2026-02-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('events', '0022_alter_event_display_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fk_office',
            field=models.ForeignKey(blank=True, db_column='fk_office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.office'),
        ),
    ]
