# Generated by Django 4.2.4 on 2026-02-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0002_alter_barangay_province'),
        ('events', '0023_event_fk_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangays.barangay'),
        ),
    ]
