# Generated by Django 4.2.4 on 2024-01-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='division_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
