# Generated by Django 4.2.4 on 2023-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgu',
            name='classification',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lgu',
            name='district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lgu',
            name='lgu_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lgu',
            name='zip_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
