# Generated by Django 4.2.4 on 2023-11-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgus', '0002_lgu_classification_lgu_district_lgu_lgu_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lgu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
