# Generated by Django 4.2.4 on 2023-11-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgoutcomes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgoutcome',
            old_name='paps',
            new_name='description',
        ),
    ]
