# Generated by Django 4.2.4 on 2023-12-01 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lgus', '0003_alter_lgu_created_at_alter_lgu_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=500)),
                ('city_mun', models.CharField(blank=True, max_length=500, null=True)),
                ('province', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lgu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgus.lgu')),
            ],
        ),
    ]
