# Generated by Django 4.2.4 on 2023-12-01 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0002_alter_province_created_at_alter_province_updated_at'),
        ('barangays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provinces.province'),
        ),
    ]
