# Generated by Django 4.2.4 on 2023-11-03 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgoutcomes', '0002_rename_paps_orgoutcome_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pap', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgoutcomes.orgoutcome')),
            ],
        ),
    ]
