
# Generated by Django 4.2.4 on 2023-11-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='oo_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
