# Generated by Django 4.2.4 on 2026-02-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='fk_office',
            field=models.ForeignKey(blank=True, db_column='fk_office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.office'),
        ),
    ]
