# Generated by Django 5.2 on 2026-03-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_division_fk_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
